---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >-
  Sample data lake

Parameters:

  Bucketname:
    Type: String
    Default: balaaws-s3-ingest-321


Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref Bucketname
      NotificationConfiguration:
        QueueConfigurations:
        - Event: s3:ObjectCreated:*
          Filter:
            S3Key:
              Rules:
              - Name: suffix
                Value: .csv
          Queue: !GetAtt IncomingSqsQueue.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ##########################################################################
  # SQS Queues
  ##########################################################################
  IncomingSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      # ContentBasedDeduplication: false
      DelaySeconds: 0
      FifoQueue: false
      # KmsDataKeyReusePeriodSeconds: 300
      # KmsMasterKeyId: !GetAtt EdmKmsKey.Arn
      # KmsMasterKeyId: alias/aws/sns
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      # QueueName: "datalakeDeleteSQS"
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt IncomingSqsQueueDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Name
          Value: !Sub "  Data Lake Incoming Queue"

  IncomingSqsQueueDLQ:
    Type: AWS::SQS::Queue
    Properties:
      # ContentBasedDeduplication: false
      DelaySeconds: 0
      # FifoQueue: false
      # KmsDataKeyReusePeriodSeconds: 300
      # KmsMasterKeyId: !GetAtt EdmKmsKey.Arn
      # KmsMasterKeyId: alias/aws/sns
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      # QueueName: "datalakeDeleteDLQ"
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 180

  # https://aws-data-wrangler.readthedocs.io/en/stable/index.html
  AwsDataWranglerLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      Description: >-
        AWS Data Wrangler Layer
      ContentUri: src/lambda_layers/aws-data-wrangler
      CompatibleRuntimes:
        - python3.8


  ##########################################################################
  # Lambda Functions
  #
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  ##########################################################################

  DataLakeRunGlueCrawler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/lambda_functions/run_glue_crawler
      Description: >-
        Runs glue Crawlers 
      Handler: app.lambda_handler
      Layers:
        - !Ref AwsDataWranglerLayer
      MemorySize: 256
      # policy templates:
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataS3BucketStackname
      Timeout: 180
      Environment:
        Variables:
          LOG_LEVEL: INFO

  IncomingStarterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/lambda_functions/workflow_starter
      Description: >-
        Entry point to the Semarchy XRef Incoming process.
        Subscribed to an SQS queue and starts the Step Function state machine
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt  IncomingSqsQueue.Arn
            BatchSize: 10
            Enabled: true
      Handler: app.lambda_handler
      Layers:
        - !Ref AwsLambdaPowertoolsPythonLayer
      MemorySize: 256
      # policy templates:
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt IncomingSqsQueue.Name
        - StepFunctionsExecutionPolicy:
            StateMachineName:
              !GetAtt IncomingProcesStateMachine.Name
      # Should match SQS queue visibility timeout
      Timeout: 180

      Environment:
        Variables:
          LOG_LEVEL: INFO
          STATE_MACHINE_ARN: !GetAtt IncomingProcesStateMachine.Arn
  ##########################################################################
  # Step Functions
  #
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-step-functions-in-sam.html
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
  ##########################################################################
  IncomingProcesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: src/state_machines/dl_automation/state_machine.asl.json
      # NOTE DefinitionSubstitutions only supports string substitutions
      # so numeric values don't work
      DefinitionSubstitutions:
        IncomingProcessFunctionArn:
          !GetAtt IncomingStarterFunction.Arn
        DeadLetterQueueUrl: !Ref IncomingSqsQueueDLQ
      # policy templates:
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
      Policies:

        - LambdaInvokePolicy:
            FunctionName: !Ref IncomingStarterFunction
        # - SQSSendMessagePolicy:
        #     QueueName: !Ref IncomingSqsQueueDLQ